export const CAMPOS_DISPONIVEIS = {
  cliente: [
    { label: 'Nome do Cliente',  value: 'cliente_nome' },
    { label: 'CPF/CNPJ',         value: 'cliente_documento' },
    { label: 'RG',               value: 'cliente_rg' },
    { label: 'Endereço',         value: 'cliente_endereco' },
    { label: 'Telefone',         value: 'cliente_telefone' },
    { label: 'Email',            value: 'cliente_email' },
    { label: 'Nacionalidade',    value: 'cliente_nacionalidade' },
    { label: 'Profissão',        value: 'cliente_profissao' },
    { label: 'Estado Civil',     value: 'cliente_estado_civil' },
    { label: 'Sexo',             value: 'cliente_sexo' },
    { label: 'Data de Nascimento', value: 'cliente_data_nascimento' },

  ],
  escritorio: [
    { label: 'Nome do Escritório', value: 'escritorio_nome' },
    { label: 'CNPJ',               value: 'escritorio_cnpj' },
    { label: 'Endereço',           value: 'escritorio_endereco' },
    { label: 'Telefone',           value: 'escritorio_telefone' },
    { label: 'Email',              value: 'escritorio_email' },
    { label: 'Cidade',             value: 'escritorio_cidade' },
    { label: 'Estado',             value: 'escritorio_estado' },
    { label: 'CEP',                value: 'escritorio_cep' },
  ],
  advogado: [
    { label: 'Nome do Advogado', value: 'advogado_nome' },
    { label: 'OAB',              value: 'advogado_oab' },
    { label: 'OAB-UF',           value: 'advogado_uf' },
    { label: 'CPF',              value: 'advogado_cpf' },
    { label: 'RG',               value: 'advogado_rg' },
    { label: 'Endereço',         value: 'advogado_endereco' },
    { label: 'Telefone',         value: 'advogado_telefone' },
    { label: 'Email',            value: 'advogado_email' },
    { label: 'Especialidade',    value: 'advogado_especialidade' },
    { label: 'Nacionalidade',    value: 'advogado_nacionalidade' },
    { label: 'Profissão',        value: 'advogado_profissao' },
    { label: 'Estado Civil',     value: 'advogado_estado_civil' },
    { label: 'Sexo',             value: 'advogado_sexo' },
    { label: 'Data de Nascimento', value: 'advogado_data_nascimento' },
  ],
  processo: [
    { label: 'Número do Processo', value: 'processo_numero' },
    { label: 'Vara',               value: 'processo_vara' },
    { label: 'Foro',               value: 'processo_foro' },
    { label: 'Parte Contrária',    value: 'processo_parte_contraria' },
  ],
  data: [
    { label: 'Data Atual (DD/MM/AAAA)',        value: 'data_completa' },
    { label: 'Dia Atual (DD)',                 value: 'data_dia' },
    { label: 'Mês Atual (MM)',                 value: 'data_mes' },
    { label: 'Ano Atual (AAAA)',               value: 'data_ano' },
    { label: 'Dia Atual (por extenso)',        value: 'data_extenso_dia' },
    { label: 'Mês Atual (por extenso)',        value: 'data_extenso_mes' },
    { label: 'Ano Atual (por extenso)',        value: 'data_extenso_ano' },
  ],
} as const;


